### ISSUE TITLE
Add commander search

### ISSUE THREAD

**Issue by Kender2** [Kender2/swc-squadranking#12]
Add functionality to find a player through search.

Results show a list of matching commanders and their squad and faction.

Question is where to place the search box or link to search page.

**Comment by MidgetAl** [comment]
I would totally love this feature.

Keep up the good work.

**Comment by MidgetAl** [comment]
Any progress on this? As I say whenever I come around here ... coding is not my thing, so feel free to tell me to fuck off ... but this feature I think would be awesome ... just to see where old friends/enemies have moved on to.

**Comment by Kender2** [comment]
I don't need help with coding this per se. But I'm having a hard time figuring out where to add the search function in the site.
For the desktop version it's easy enough to put a link, button or searchbox somewhere, but since most users are on mobiles (62% mobile, 18% tablet, 20% desktop) I prefer an elegant and intelligent solution.

**Comment by eric-vNext** [comment]
Maybe something like this?

http://bootsnipp.com/snippets/GzXXl

Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Dec 29, 2016 at 10:03 AM -0500, "Kender2" <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't need help with coding this per se. But I'm having a hard time figuring out where to add the search function in the site.
For the desktop version it's easy enough to put a link, button or searchbox somewhere, but since most users are on mobiles (62% mobile, 18% tablet, 20% desktop) I prefer an elegant and intelligent solution.

**Comment by spariev** [comment]
oh snap, should have checked out the issue before coding the PR. Anyway, snippet with dropdown looks nice, should be easy to integrate.

**Comment by Kender2** [comment]
Done
